---

##########################################################################
# Configuration options for the Plone Ansible Playbook
# All these are discussed in the documentation.
#
# Unless you have forked your playbook, you should probably not customize
# this file, as changes will be overwritten by pulls.
#
# Instead, create and edit local-configure.yml
##########################################################################


#######################################
# System options

admin_email:

motd: |
    This server is configured via Ansible.
    Do not change configuration settings directly.

auto_upgrades: yes

additional_packages: []


#######################################
# Plone options

plone_major_version: 4.3

plone_version: 4.3.3

python_version: 2.7

target_path: /usr/local/plone-{{ plone_major_version }}

var_path: /var/local/plone-{{ plone_major_version }}

backup_path:

instance_name: zeoserver

buildout_git_repo: no

buildout_git_version: master

initial_password: admin

client_count: 2

zodb_cache_size: 30000

zserver_threads: 1

client_max_memory: 0

# additional_eggs:
#     - Products.PloneFormGen

# additional_versions:
#      - "Products.PloneFormGen = 1.7.16"
#      - "Products.PythonField = 1.1.3"
#      - "Products.TALESField = 1.1.3"

zeo_port: 8100

client_base_port: 8080

environment_vars:
  - "PYTHON_EGG_CACHE {{ var_path }}/.python-eggs"

autorun_buildout: yes

buildout_cache_url: http://dist.plone.org/release/{{ plone_version }}/buildout-cache.tar.bz2

buildout_cache_file:


#######################################
# Cron jobs

pack_at:
  minute: 30
  hour: 1
  weekday: 7

keep_days: 3

backup_at:
  minute: 30
  hour: 2
  weekday: "*"

keep_backups: 3

keep_blob_days: 21


#######################################
# Load-balancer options

install_loadbalancer: yes

loadbalancer_port: 8080

loadbalancer_monitor_port: 1080


#######################################
# Caching proxy options

install_proxycache: yes

proxycache_port: 6081

proxycache_method: malloc

proxycache_size: 256m


#######################################
# Web-server options

install_webserver: yes

webserver_virtualhosts:
  - hostname: localhost
    aliases:
      - default
    zodb_path: /Plone


#######################################
# Mail-server options

install_mailserver: yes

mailserver_relayhost:

mailserver_relayport:

mailserver_relayuser:

mailserver_relaypassword:


#######################################
# Monitoring options

install_muninnode: yes

munin_node_port: 4949

muninnode_query_ips:
    - ^127\.0\.0\.1$

install_logwatch: yes

install_fail2ban: yes


#########################
# Supervisor options

supervisor_config_dir: "/etc/supervisor/conf.d/"
redirect_stderr: "false"
autorestart: "unexpected"
startsecs: 1
stopwaitsecs: 10
autostart: "true"
task_env_vars: {}
