---

# NOTE: This playbook *adds* rules.
# It does not delete existing rules.

- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:

  - name: Include vars from local-configure.yml if found
    include_vars: "{{ item }}"
    with_first_found:
     - local-configure.yml
     - null.yml

  - include: firewalls/debian-ufw.yml
    when: ansible_os_family == 'Debian'

  - include: firewalls/centos-firewalld.yml
    when: ansible_os_family == 'RedHat'

