---

# plone.org configuration
#
# This currently targets::
#
#     RAM: 2048MB
#     Cores: 2

# Update to admins@plone.org for live
admin_email: stevem@plone.org

plone_initial_password: admin

muninnode_query_ips:
    - 50.1.20.238


# Plone settings
# --------------

plone_version: '5.1a1'

plone_client_count: 2
plone_zodb_cache_size: 15000
plone_client_max_memory: 750MB

plone_additional_eggs:
  - ploneorg.core
  - authomatic
  - pas.plugins.authomatic
  - collective.workspace
  - collective.isotope
  - Products.PloneFormGen
  - collective.recaptcha
  - simplejson
  - Products.PloneHotfix20160419
  - plone.app.changeownership
  - Products.PloneHotfix20160830
  - Products.PloneHotfix20161129
  - Products.PloneHotfix20170117

plone_sources:
  - "ploneorg.core = git https://github.com/plone/ploneorg.core.git"
  - "ploneorg.theme = git https://github.com/plone/ploneorg.theme.git pushurl=git@github.com:plone/ploneorg.theme.git"
  - "Py-StackExchange = git https://github.com/lucjon/Py-StackExchange.git"
  - "plone.app.vulnerabilities = git https://github.com/plone/plone.app.vulnerabilities.git pushurl=git@github.com:plone/plone.app.vulnerabilities.git"
  - "collective.workspace = git https://github.com/collective/collective.workspace.git pushurl=git@github.com:collective/collective.workspace.git branch=plone5"
  - "collective.roster = git https://github.com/collective/collective.roster.git pushurl=git@github.com:collective/collective.roster.git"
  - "collective.badge = git https://github.com/collective/collective.badge.git pushurl=git@github.com:collective/collective.badge.git"
  - "pas.plugins.authomatic = git https://github.com/collective/pas.plugins.authomatic.git pushurl=git@github.com:collective/pas.plugins.authomatic.git"
  - "collective.isotope = git git://github.com/collective/collective.isotope.git pushurl=git@github.com:collective/collective.isotope.git"
  - "plone.app.changeownership = git https://github.com/collective/plone.app.changeownership.git pushurl=https://github.com/collective/plone.app.changeownership.git branch=new-owner-text-field"

plone_additional_versions:
  - "check-manifest = 0.25"
  - "collective.jsonmigrator = 0.2"
  - "corneti.recipes.codeintel = 0.3"
  - "flake8 = 2.4.1"
  - "MarkupSafe = 0.23"
  - "mccabe = 0.3.1"
  - "plone.app.transmogrifier = 1.3"
  - "plone.recipe.codeanalysis = 2.1"
  - "pycountry = 1.17"
  - "pyflakes = 0.8.1"
  - "PyGithub = 1.25.2"
  - "requests = 2.8.1"
  - "setuptools = "
  - "transmogrify.dexterity = 1.6.1"
  - "twitter = 1.17.1"
  - "z3c.jbot = 0.7.2"
  - "zc.buildout = "
  - "Authomatic = 0.1.0.post1"
  - "Products.PloneHotfix20160419 = 1.0"
  - "collective.themefragments = 1.0.1"
  - "Products.PloneFormGen = 1.8.0"
  - "Products.PythonField = 1.1.3"
  - "Products.TemplateFields = 1.2.5"
  - "Products.TALESField = 1.1.3"
  - "wadllib = 1.3.2"
  - "launchpadlib = 1.10.3"
  - "testresources = 2.0.0"
  - "lazr.restfulclient = 0.13.1"
  - "keyring = 9.0"
  - "httplib2 = 0.9.2"
  - "pbr = 1.9.1"
  - "wsgi-intercept = 1.2.2"
  - "oauth = 1.0.1"
  - "lazr.uri = 1.0.3"
  - "lazr.authentication = 0.1.3"
#  - "pas.plugins.authomatic = 1.0a6"
  - "Products.PloneHotfix20160830 = 1.0"
  - "Products.PloneHotfix20161129 = 1.2"
  - "Products.PloneHotfix20170117 = 1.0"
  - "collective.recaptcha = 2.0.0"
  - "norecaptcha = 0.3.0"

# Nginx settings

webserver_virtualhosts:
  - hostname: barcelona.plone.org
    protocol: http
    extra: return 301 https://$server_name$request_uri;

  - hostname: barcelona.plone.org
    zodb_path: /ploneorg
    port: 443
    protocol: https
    certificate:
      key: /etc/nginx/ssl/wildcard.key
      crt: /etc/nginx/ssl/wildcard.crt
    extra:
      - rewrite ^/help /support redirect;
      - rewrite ^/edu /community/edu redirect;

  - hostname: barcelona_direct.plone.org
    zodb_path: /ploneorg
    port: 443
    protocol: https
    certificate:
      key: /etc/nginx/ssl/wildcard.key
      crt: /etc/nginx/ssl/wildcard.crt
    extra:
      - rewrite ^/help /support redirect;
      - rewrite ^/edu /community/edu redirect;

  - hostname: barcelona_direct.plone.org
    zodb_path: /ploneorg
    extra:
      - rewrite ^/help /support redirect;
      - rewrite ^/edu /community/edu redirect;

  - hostname: new.plone.org
    zodb_path: /ploneorg
  - hostname: www.plone.org
    extra:
      - return 301 https://plone.org$request_uri;

  - hostname: plone.org
    default_server: yes
    extra: return 301 https://$server_name$request_uri;

  - hostname: plone.org
    default_server: yes
    zodb_path: /ploneorg
    port: 443
    protocol: https
    certificate:
      key: /etc/nginx/ssl/wildcard.key
      crt: /etc/nginx/ssl/wildcard.crt
    extra:
      - rewrite ^/help /support redirect;
      - rewrite ^/edu /community/edu redirect;
      - rewrite ^/documentation/kb/installing-add-ons-quick-how-to http://docs.plone.org/manage/installing/installing_addons.html redirect;
      - rewrite ^/upgrade http://docs.plone.org/manage/upgrading/index.html redirect;
      - rewrite ^/donate https://plone.org/sponsors redirect;
      - rewrite ^/products /download redirect;
      - rewrite ^/jobs https://community.plone.org/c/jobs redirect;
      - rewrite ^/providers https://plone.com/providers redirect;
      - rewrite ^/wpd https://plone.org/events/wpd redirect;

additional_packages:
  - nodejs-legacy
  - nodejs
  - npm
