---

- hosts: all
  sudo: yes
  gather_facts: yes


  pre_tasks:

    - name: Fail if Ansible is old
      fail:
        msg: "We have only tested with Ansible version 1.2+. Please update Ansible"
      when: ansible_product_version < '1.2'

    - name: Include vars from configure.yml
      include_vars: configure.yml
      tags:
        - plone
        - haproxy
        - varnish
        - postfix
        - logwatch
        - munin
        - motd
        - nginx
        - timezone

    - name: Include vars from local-configure.yml if found
      include_vars: "{{ item }}"
      with_first_found:
       - local-configure.yml
       - null.yml
      tags:
        - plone
        - haproxy
        - varnish
        - postfix
        - logwatch
        - munin
        - motd
        - nginx
        - timezone

    - name: Fail if no administrative email set
      fail:
        msg: "You must set the admin_email variable."
      when: not admin_email
      tags:
        - plone
        - haproxy
        - varnish
        - postfix
        - logwatch
        - munin
        - motd
        - nginx

    - name: Update host
      apt: upgrade=dist update_cache=yes

    - name: Ensure optional packages
      apt: pkg={{ item }} state=present
      with_items: additional_packages


  roles:

    - role: ANXS.hostname

    - role: jnv.unattended-upgrades
      when: auto_upgrades
      unattended_mail: root
      unattended_origins_patterns:
        - 'origin=${distro_id},archive=${distro_codename}-security'
        - 'o=${distro_id},a=${distro_codename}'
        - 'o=${distro_id},a=${distro_codename}-updates'

    - role: tersmitten.fail2ban
      when: install_fail2ban
      tags: fail2ban

    - role: plone.plone_server
      plone_instance_name: primary_plone
      plone_target_path: /opt/primary_plone
      plone_var_path: /var/local/primary_plone
      plone_major_version: '5.0'
      plone_version: '5.0'
      plone_initial_password: admin
      plone_zeo_port: 5100
      plone_client_base_port: 5081
      plone_client_count: 2
      # plone_create_site: no

    - role: plone.plone_server
      plone_instance_name: secondary_plone
      plone_target_path: /opt/secondary_plone
      plone_var_path: /var/local/secondary_plone
      plone_major_version: '4.3'
      plone_version: '4.3.7'
      plone_initial_password: admin
      plone_zeo_port: 4100
      plone_client_base_port: 4081
      plone_client_count: 3
      # plone_create_site: no

    - role: haproxy
      when: install_loadbalancer
      tags: haproxy
      cluster:
        - name: plone5_cluster
          port: 5080
          client_base_port: 5081
          client_count: 1
          plone_zodb_cache_size: 5000
        - name: plone4_cluster
          port: 4080
          client_base_port: 4081
          client_count: 1
          plone_zodb_cache_size: 5000

    - role: varnish
      when: install_proxycache
      tags: varnish
      proxycache_method: file
      backends:
        - name: plone5
          port: 5080
          hostnames:
            - lumpy
        - name: plone4
          port: 4080
          hostnames:
            - lumpyanon

    - role: nginx
      when: install_webserver
      tags: nginx
      webserver_virtualhosts:
        - hostname: lumpy
          zodb_path: /Plone
          aliases:
            - default
        - hostname: lumpyanon
          zodb_path: /Plone

    # - role: postfix
    #   when: install_mailserver
    #   tags: postfix

    # - role: logwatch
    #   when: install_logwatch
    #   tags: logwatch

    # - role: munin-node
    #   when: install_muninnode
    #   tags: munin

    # - role: restart_script
    #   tags: restart_script

  tasks:

    # - name: Update MOTD
    #   tags: motd
    #   template:
    #     dest: /etc/motd
    #     src: templates/motd.j2

    - name: Set timezone variables
      tags: timezone
      copy: content={{ timezone }}
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

