---

- hosts: all
  sudo: yes
  gather_facts: yes


  pre_tasks:

    - name: Include vars from configure.yml
      include_vars: configure.yml

    - name: Include vars from local-configure.yml if found
      include_vars: "{{ item }}"
      with_first_found:
       - local-configure.yml
       - null.yml

    - name: Fail if no administrative email set
      fail:
        msg: "You must set the admin_email variable."
      when: not admin_email

    - name: Update host
      apt: upgrade=dist update_cache=yes

    - name: Ensure required packages
      apt: pkg={{ item }} state=present
      with_items:
        - build-essential
        - python-dev
        - python-pip

    - name: Ensure optional packages
      apt: pkg={{ item }} state=present
      with_items: additional_packages

    - name: Ensure recent python-virtualenv
      pip: name=virtualenv
      # note that this installs to /usr/local/bin
      # which is not automatically on the path


  roles:

    - role: jnv.unattended-upgrades
      when: auto_upgrades
      unattended_mail: root
      unattended_origins_patterns:
        - 'origin=${distro_id},archive=${distro_codename}-security'
        - 'o=${distro_id},a=${distro_codename}'
        - 'o=${distro_id},a=${distro_codename}-updates'

    - role: tersmitten.fail2ban
      when: install_fail2ban

    - role: plone

    - role: haproxy
      when: install_loadbalancer

    - role: varnish
      when: install_proxycache

    - role: postfix
      when: install_mailserver

    - role: logwatch
      when: install_logwatch

    - role: munin-node
      when: install_muninnode


  tasks:

    - name: Update MOTD
      template:
        dest: /etc/motd
        src: templates/motd.j2
