---

- hosts: all
  sudo: yes
#  gather_facts: yes
  gather_facts: no


  pre_tasks:

    - name: Include vars from configure.yml
      include_vars: configure.yml

    - name: Include vars from local-configure.yml if found
      include_vars: "{{ item }}"
      with_first_found:
       - local-configure.yml
       - null.yml

    # - name: Update host
    #   apt: upgrade=dist update_cache=yes

    # - name: Ensure required packages
    #   apt: pkg={{ item }} state=present
    #   with_items:
    #     - build-essential
    #     - python-dev
    #     - python-pip
    #     - mailutils

    # - name: Ensure recent python-virtualenv
    #   pip: name=virtualenv
    #   # note that this installs to /usr/local/bin
    #   # which is not automatically on the path


  roles:

    # - role: jnv.unattended-upgrades
    #   when: auto_upgrades
    #   unattended_mail: root
    #   unattended_origins_patterns:
    #     - 'origin=${distro_id},archive=${distro_codename}-security'
    #     - 'o=${distro_id},a=${distro_codename}'
    #     - 'o=${distro_id},a=${distro_codename}-updates'

    # - role: tersmitten.fail2ban
    #   when: install_fail2ban

    - role: plone

  tasks:

    # - name: Update motd
    #   copy:
    #     dest=/etc/motd
    #     content="{{ motd }}"

