---

# Create users and add their public keys.
# Users are created without initial passwords, so they'll need
# their private keys to log in. Following login, they will need
# to set a password before using sudo.

- hosts: all
  sudo: yes
  gather_facts: no

  vars:
    users:
      - name: steve
        groups: sudo
        auth_key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6IMFOP2K/n2UbtP29d9hU1Ae9vkxpCtd87H7PX5xBfjsh1Tkvq3rRE+Jr6pzPja4gPRCikLm3fV3PdEp4eh1OaSP4SnuBFWcHOpxdDuU+pjNdGMBZlQqjzC0cxjAvW7ZtnT7YHYzH6zHr+t7Z8IESsnw7idDUCupr4Zqot7PaylnI4NLb1zQQxyD+XnjPRu8Ne/0JSyKizkCkXhUuYDbvRYFAs/jFm3pmurodrOx62cwVpdztsHiK5mdTwIQhObzSb3ZnDLNNfXO3yUcX9kWJ6eQ9iP5whw2OBddf+2EoCZtshYIqtGNYaFFdf8tGF5ZwugCHxe/gzlzDMVb9ZM49w== steve@dcn.org
      - name: fulvio
        groups: sudo
        auth_key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA7GERk76wrx4ih37ulyRZwFRhT4HvhKXUadqQ1cmosEQfOA9Z7SQDxqMjzNvxakuF+4RiZd0NpmenN/R1yg1+PN0pzPd5W0xNpqKUJE5C+l6bFoeCkFhCqOlVSn1JigBNXkeQ0AlweIhhb3RPbPP1iYX0sLidBmmRnq+4+1+AFHLDWsj2jI7nyvpDfU5nM0BNQJHqsedkQkbYSrPtGK4ZnnLXqdLI4qGtomvMa4yu3G9Cn71Sfr6wFaPQ7mE0o66/NiSR3d0f92Ek6KEvn7Yqcysd2zf9Gm4coi3NfIdtVkkbBAKD2W6RnDipma/mN/1kbqzVqpn/lOn9lTnpRGVNUw== fulvio@Macintosh-2.local
      - name: sneridagh
        groups: sudo
        auth_key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1Sy0WqIJ5axkJybkN128krc4nJAUtcYidh+VHZYAGCH7xezrI3cB87CWQfI5ALCzrhLsPiquceuuWhca9WPtvP0SdP05Vs+djtzSgKbgmSdAhcefT5tlKH775XCcesqK64YZU+FXm1+LUIST7yXU+fXHSlBsWd2c59clj9mMEmqUdHDH2HrRZC2xzveR22XfKlKkxMrTmhwofkp+g9PYoeJjfXUCYX4Ia/vbCQoKPcovMEQH0BEQ+GOGKxV0W1oFtu3X4f3dl/TwC6Mz/8ESe2cQ7Ae7q99o+pl3NEMjiZQFonszidB26QoXXmjI1n/pc0mwm8INsL1GcPJEFEJedw== sneridagh@gmail.com


  tasks:

    - name: Add users
      user:
        name={{ item.name }}
        groups={{ item.groups }}
        shell=/bin/bash
        password=
      with_items: users

    - name: Add .ssh directories
      file:
        path=/home/{{ item.name }}/.ssh
        state=directory
        owner={{ item.name }}
      with_items: users

    - name: Add keys
      lineinfile:
        dest=/home/{{ item.name }}/.ssh/authorized_keys
        state=present
        create=yes
        line="{{ item.auth_key }}"
        owner={{ item.name }}
      with_items: users
