---

- include: "{{ ansible_os_family }}.yml"

- name: Configure munin-node
  template:
    src=munin-node.conf.j2
    dest=/etc/munin/munin-node.conf
    owner=root
    group=root
    mode=644
  notify: restart munin-node

- name: Add custom plone monitor
  copy:
    src=monitors/plonezope_res
    dest=/etc/munin/plugins/
    mode=775
  notify: restart munin-node

- name: Add custom haproxy monitors
  copy:
    src=monitors/haproxy/
    dest=/etc/munin/plugins/
    mode=775
  when: install_loadbalancer|default(True)
  notify: restart munin-node

- name: Add standard haproxy monitor for backend
  file:
    path="/etc/munin/plugins/haproxy_backend"
    state=link
    src="/usr/share/munin/plugins/haproxy_"
  when: install_loadbalancer|default(True)
  notify: restart munin-node

- name: Configure custom haproxy monitors
  template:
    src=haproxy.j2
    dest=/etc/munin/plugin-conf.d/
  when: install_loadbalancer|default(True)
  notify: restart munin-node

- name: Add standard varnish monitor for hit rate
  file:
    path="/etc/munin/plugins/varnish_hit_rate"
    state=link
    src="/usr/share/munin/plugins/varnish_"
  when: install_proxycache|default(True)
  notify: restart munin-node

- name: Deactivate unneeded monitors
  file:
    path="/etc/munin/plugins/{{ item }}"
    state=absent
  with_items:
    - nfs4_client
    - nfs_client
    - nfsd
    - nfsd4
    - ntp_kernel_err
    - ntp_kernel_pll_freq
    - ntp_kernel_pll_off
    - ntp_offset
    - if_dummy0
    - if_err_dummy0
    - if_err_eth0
    - if_err_gre0
    - if_err_gretap0
    - if_err_ip6gre0
    - if_err_ip6tnl0
    - if_err_ip6_vti0
    - if_err_ip_vti0
    - if_err_teql0
    - if_err_tunl0
    - if_gre0
    - if_gretap0
    - if_ip6gre0
    - if_ip6tnl0
    - if_ip6_vti0
    - if_ip_vti0
    - if_teql0
    - if_tunl0
    - irqstats
    - users
    - proc_pri
  notify: restart munin-node

- name: Add desired monitors
  file:
    path="/etc/munin/plugins/{{ item }}"
    state=link
    src="/usr/share/munin/plugins/{{ item }}"
  with_items:
    - http_loadtime
    - nginx_request
    - nginx_status
  notify: restart munin-node

- name: Assure munin running at end of playbook
  command: /bin/true
  notify: munin-node started
