---

- name: Postfix present
  apt: pkg=postfix state=present

- name: Set mynetworks_style to host (forward local only)
  lineinfile:
    dest=/etc/postfix/main.cf
    state=present
    line="mynetworks_style = host"
  notify:
  - reload postfix

- name: Set aliases
  template:
    src=aliases
    dest=/etc/aliases
    owner=root
    group=root
    mode=644
  notify:
  - new aliases
