---

- name: logwatch package installed
  apt: pkg={{ item }} state=present
  with_items:
    - logwatch

- name: update-notifier-common installed
  apt: pkg={{ item }} state=present
  with_items:
    - update-notifier-common
  ignore_errors: True

- name: Check our update notify technology
  stat:
    path: /etc/update-motd.d
  register: have_update_motd_d

# - debug:
#     var: have_update_motd_d.stat.exists
